What is pytorch?

This notebook is an replication of [the official tutorial](https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py).

Pytorch is 
- A replacement for NumPy to use the power of GPUs (Existence of GPU is preferable.)
- a deep learning research platform that provides maximum flexibility and speed (flexible implementation)

# Tensors

In [1]:
!pip show jupyterlab_code_formatter

Name: jupyterlab-code-formatter
Version: 1.3.5
Summary: Server extension to power `@ryantam626/jupyterlab_code_formatter` npm package.
Home-page: https://github.com/ryantam626/jupyterlab_code_formatter
Author: Ryan Tam
Author-email: ryantam626@gmail.com
License: MIT
Location: /opt/conda/lib/python3.7/site-packages
Requires: notebook, packaging
Required-by: 


In [2]:
!jupyter labextension list

JupyterLab v2.0.0
Known labextensions:
   app dir: /opt/conda/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v1.1.0  enabled   X
        @lckr/jupyterlab_variableinspector v0.5.1  enabled  OK
        @ryantam626/jupyterlab_code_formatter v1.2.0  enabled  OK
        jupyterlab_bokeh v1.0.0  enabled   X

   The following extension are outdated:
        @jupyter-widgets/jupyterlab-manager
        jupyterlab_bokeh
        
   Consider running "jupyter labextension update --all" to check for updates.



In [3]:
!jupyter serverextension list

config dir: /home/jovyan/.jupyter
    jupyterlab_code_formatter  enabled 
    - Validating...
      jupyterlab_code_formatter  OK
config dir: /opt/conda/etc/jupyter
    jupyterlab  enabled 
    - Validating...
      jupyterlab 2.0.0 OK


In [1]:
from __future__ import print_function
import torch

Uninitialized

In [4]:
x = torch.empty(5,3)
print(x)

tensor([[-7.4280e+15,  4.5748e-41, -2.3355e+20],
        [ 3.0625e-41, -2.0256e+14,  4.5748e-41],
        [-2.0256e+14,  4.5748e-41, -2.0256e+14],
        [ 4.5748e-41, -2.0256e+14,  4.5748e-41],
        [-2.0256e+14,  4.5748e-41, -2.0256e+14]])


Random

In [6]:
x = torch.rand(5, 3)
print(x)

tensor([[0.6489, 0.3213, 0.3325],
        [0.2257, 0.7997, 0.9630],
        [0.3483, 0.2122, 0.5629],
        [0.2452, 0.2674, 0.4637],
        [0.0753, 0.0282, 0.6881]])


Filed with 0

In [2]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [8]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


Tensor to tensor

In [12]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.2425,  0.4919,  0.4565],
        [-0.2388, -2.0493,  0.3450],
        [ 0.1156,  0.3669,  0.2846],
        [ 2.6290,  0.6491,  1.1453],
        [ 1.4072,  1.2652, -0.3454]])


In [15]:
print(x.size())

torch.Size([5, 3])


# Operations

Addition: syntax 1

In [16]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 0.2653,  1.1735,  1.4205],
        [ 0.6081, -1.8097,  1.1224],
        [ 0.8902,  1.1286,  0.8853],
        [ 3.0546,  0.9947,  1.3882],
        [ 1.4961,  1.8090,  0.0209]])


Addition: syntax 2

In [17]:
print(torch.add(x, y))

tensor([[ 0.2653,  1.1735,  1.4205],
        [ 0.6081, -1.8097,  1.1224],
        [ 0.8902,  1.1286,  0.8853],
        [ 3.0546,  0.9947,  1.3882],
        [ 1.4961,  1.8090,  0.0209]])


Addition: providing an output tensor as argument

In [18]:
result = torch.empty(5,3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.2653,  1.1735,  1.4205],
        [ 0.6081, -1.8097,  1.1224],
        [ 0.8902,  1.1286,  0.8853],
        [ 3.0546,  0.9947,  1.3882],
        [ 1.4961,  1.8090,  0.0209]])


Addition in-place

In [19]:
y.add_(x)
print(y)

tensor([[ 0.2653,  1.1735,  1.4205],
        [ 0.6081, -1.8097,  1.1224],
        [ 0.8902,  1.1286,  0.8853],
        [ 3.0546,  0.9947,  1.3882],
        [ 1.4961,  1.8090,  0.0209]])


Index

In [20]:
print(x[:, 1])

tensor([ 0.4919, -2.0493,  0.3669,  0.6491,  1.2652])


Resize tensor with .view()

In [21]:
x = torch.randn(4,4)
y = x.view(16)
z= x.view(-1, 2)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([8, 2])


There are many other operations [here](https://pytorch.org/docs/stable/torch.html).

# Numpy Bridge

Convert to numpy. They share the same memory.

In [22]:
a = torch.ones(6)
print(a)

tensor([1., 1., 1., 1., 1., 1.])


In [23]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1. 1.]


In [24]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2. 2.]


From numpy to tensor

In [25]:
import numpy as np
a = np.ones(6)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2., 2.], dtype=torch.float64)


# CUDA Tensors

In [27]:
torch.cuda.is_available()

False

In [26]:
if torch.cuda.is_available():
    device = torch.device('cuda')
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))